DEFAULT_WORKBENCH_COLUMNS = [
    "ID",
    "工单名称",
    "工单类型",
    "工单耗时",
    "COT名称",
    "API Order",
    "API Part 1",
    "API Part 2",
    "API Part 3",
    "API Part 4",
    "API Part 5",
    "API Part 6",
    "API Part 7",
    "Summary",
    "标注数据",
    "情感分类",
    "GPT4_标注",
    "Claude_结果",
]
